######################################################################
# Automatically generated by qmake (2.01a) Mon Jan 10 21:42:35 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . code tests ui
INCLUDEPATH += . ui code

# Input
HEADERS += code/lydict.h code/lyword.h ui/imp_dictedit.h
FORMS += ui/dictedit.ui
SOURCES += main.cpp \
           code/lydict.cpp \
           code/lyword.cpp \
           ui/imp_dictedit.cpp
