######################################################################
# Automatically generated by qmake (2.01a) Mon Mar 7 16:57:20 2011
######################################################################

TEMPLATE = lib
TARGET = lyngo
DEPENDPATH += . examples
INCLUDEPATH += .
# CONFIG += static

# Input
HEADERS += LyDict.h LyGrade.h LyQuestion.h LyQuiz.h LyWord.h
SOURCES += LyDict.cpp \
           LyGrade.cpp \
           LyQuestion.cpp \
           LyQuiz.cpp \
           LyWord.cpp
