######################################################################
# Automatically generated by qmake (2.01a) Sat Jan 15 10:43:29 2011
######################################################################

TEMPLATE = app
TARGET = question
DEPENDPATH += .
INCLUDEPATH += . ../
CONFIG += debug

mac {
    CONFIG -= app_bundle
    CONFIG -= debug
}

# Input
SOURCES += question.cpp \
          ../LyQuestion.h \
          ../LyQuestion.cpp
