######################################################################
# Automatically generated by qmake (2.01a) Sat Jan 15 10:43:29 2011
######################################################################

TEMPLATE = app
TARGET = question
DEPENDPATH += .
INCLUDEPATH += . ../

mac {
    CONFIG -= app_bundle
}

# Input
SOURCES += question.cpp \
          ../LyQuestion.h \
          ../LyQuestion.cpp
