######################################################################
# Automatically generated by qmake (2.01a) Sat Jan 15 11:21:50 2011
######################################################################

TEMPLATE = app
TARGET = quiz
DEPENDPATH += .
INCLUDEPATH += . ../
CONFIG += debug
LIBS += -L.. -llyngo

unix {
    QMAKE_LFLAGS += -Wl,--rpath=\\\$\$ORIGIN/..
}

mac {
    CONFIG -= app_bundle
    CONFIG -= debug
}

# Input
SOURCES += quiz.cpp
