######################################################################
# Automatically generated by qmake (2.01a) Sat Jan 15 11:21:50 2011
######################################################################

TEMPLATE = app
TARGET = quiz
DEPENDPATH += .
INCLUDEPATH += . ../

mac {
    CONFIG -= app_bundle
}

# Input
SOURCES += quiz.cpp \
           ../LyQuiz.h \
           ../LyQuiz.cpp
