######################################################################
# Automatically generated by qmake (2.01a) Sun Jan 9 10:19:30 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += imp_drillbit.h
FORMS += drillbit.ui
SOURCES += imp_drillbit.cpp main.cpp
