######################################################################
# Automatically generated by qmake (2.01a) Mon Jan 10 20:07:37 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += lydict.h lyword.h
SOURCES += dict.cpp lydict.cpp lyword.cpp
