######################################################################
# Automatically generated by qmake (2.01a) Wed Dec 29 12:53:14 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += lydict.h
SOURCES += dict.cpp lydict.cpp
